import type { EquipmentDefinition } from "../../domain/equipment/Equipment";

const commonEvidence = (sourceDocumentId: string) => [{ sourceDocumentId, note: "Pilot dataset source. Placeholder/dev status is explicit where used." }];

export const pilotEquipmentCatalog: EquipmentDefinition[] = [
  {
    id: "rgt-100-ksva-100",
    category: "boiler",
    name: "Котел RGT-100 / КСВА-100",
    manufacturer: "КОМПАС",
    model: "RGT-100",
    dimensions: { widthMm: 689, depthMm: 720, heightMm: 1100 },
    serviceZones: { frontMm: 1000, rearMm: 600, leftMm: 500, rightMm: 500 },
    technicalParameters: {
      powerKw: 99,
      fuel: "natural_gas",
      gasFlowM3h: 12,
      gasPressureKpaMax: 3,
      flueDnMm: 200,
    },
    connectionPoints: [
      { id: "supply", type: "supply", label: "Подача DN32", localX: 560, localY: 120, localZ: 950, dnMm: 32, direction: "top", medium: "water", source: "pilot/passport candidate", confidence: 0.65, status: "passport" },
      { id: "return", type: "return", label: "Обратка DN32", localX: 130, localY: 120, localZ: 950, dnMm: 32, direction: "top", medium: "water", source: "pilot/passport candidate", confidence: 0.65, status: "passport" },
      { id: "gas", type: "gas", label: "Газ DN25", localX: 345, localY: 720, localZ: 420, dnMm: 25, direction: "bottom", medium: "natural_gas", source: "pilot/passport candidate", confidence: 0.55, status: "passport" },
      { id: "flue", type: "flue", label: "Дымоход DN200", localX: 345, localY: 70, localZ: 1100, dnMm: 200, direction: "up", medium: "flue_gas", source: "pilot/passport candidate", confidence: 0.55, status: "passport" },
      { id: "electric", type: "electric", label: "Электропитание", localX: 665, localY: 360, localZ: 900, direction: "right", medium: "electricity", source: "pilot placeholder", confidence: 0.35, status: "placeholder" },
      { id: "signal", type: "signal", label: "Аварийный сигнал", localX: 665, localY: 455, localZ: 900, direction: "right", medium: "signal", source: "pilot placeholder", confidence: 0.35, status: "placeholder" },
    ],
    symbols: { plan: "boiler", schematic: "boiler" },
    evidenceLinks: commonEvidence("rgt-100-ksva-100"),
    sourceStatus: "passport",
    confidence: 0.65,
    metadata: { pilot: true },
  },
  {
    id: "supply-header",
    category: "header",
    name: "Коллектор подачи STOUT SDG-0016-005002 DN32, 2 контура",
    manufacturer: "STOUT",
    model: "SDG-0016-005002",
    dimensions: { widthMm: 835, depthMm: 130, heightMm: 280 },
    serviceZones: { frontMm: 150, rearMm: 150, leftMm: 150, rightMm: 150 },
    technicalParameters: { dnMm: 32, circuits: 2, pnBar: 4, maxTemperatureC: 110, maxFlowM3h: 6.5 },
    connectionPoints: [
      { id: "supply-main", type: "supply", label: "Вход коллектора DN32", localX: 0, localY: 65, localZ: 1200, dnMm: 32, direction: "left", medium: "water", source: "pilot/passport candidate", confidence: 0.65, status: "passport" },
      { id: "supply-out-1", type: "supply", label: "Контур 1 DN25", localX: 355, localY: 0, localZ: 1200, dnMm: 25, direction: "top", medium: "water", source: "pilot/passport candidate", confidence: 0.55, status: "passport" },
      { id: "supply-out-2", type: "supply", label: "Контур 2 DN25", localX: 480, localY: 0, localZ: 1200, dnMm: 25, direction: "top", medium: "water", source: "pilot/passport candidate", confidence: 0.55, status: "passport" },
    ],
    symbols: { plan: "header", schematic: "header" },
    evidenceLinks: commonEvidence("stout-sdg-0016-005002"),
    sourceStatus: "passport",
    confidence: 0.62,
    metadata: { pilot: true },
  },
  {
    id: "return-header",
    category: "header",
    name: "Коллектор обратки STOUT SDG-0016-005002 DN32, 2 контура",
    manufacturer: "STOUT",
    model: "SDG-0016-005002",
    dimensions: { widthMm: 835, depthMm: 130, heightMm: 280 },
    serviceZones: { frontMm: 150, rearMm: 150, leftMm: 150, rightMm: 150 },
    technicalParameters: { dnMm: 32, circuits: 2, pnBar: 4, maxTemperatureC: 110, maxFlowM3h: 6.5 },
    connectionPoints: [
      { id: "return-main", type: "return", label: "Вход коллектора DN32", localX: 0, localY: 65, localZ: 1200, dnMm: 32, direction: "left", medium: "water", source: "pilot/passport candidate", confidence: 0.65, status: "passport" },
      { id: "return-out-1", type: "return", label: "Контур 1 DN25", localX: 355, localY: 130, localZ: 1200, dnMm: 25, direction: "bottom", medium: "water", source: "pilot/passport candidate", confidence: 0.55, status: "passport" },
      { id: "return-out-2", type: "return", label: "Контур 2 DN25", localX: 480, localY: 130, localZ: 1200, dnMm: 25, direction: "bottom", medium: "water", source: "pilot/passport candidate", confidence: 0.55, status: "passport" },
    ],
    symbols: { plan: "header", schematic: "header" },
    evidenceLinks: commonEvidence("stout-sdg-0016-005002"),
    sourceStatus: "passport",
    confidence: 0.62,
    metadata: { pilot: true },
  },
  {
    id: "ball-valve-dn32-supply",
    category: "valve",
    name: "Кран шаровой DN32, подача",
    manufacturer: "DN",
    model: "BV3232P",
    dimensions: { widthMm: 165, depthMm: 78, heightMm: 130 },
    serviceZones: { frontMm: 80, rearMm: 80, leftMm: 80, rightMm: 80 },
    technicalParameters: { dnMm: 32, valveType: "ball_valve" },
    connectionPoints: [
      { id: "inlet", type: "supply", label: "Вход DN32", localX: 0, localY: 39, localZ: 1100, dnMm: 32, direction: "left", medium: "water", source: "pilot/catalog", confidence: 0.45, status: "catalog" },
      { id: "outlet", type: "supply", label: "Выход DN32", localX: 165, localY: 39, localZ: 1100, dnMm: 32, direction: "right", medium: "water", source: "pilot/catalog", confidence: 0.45, status: "catalog" },
    ],
    symbols: { plan: "valve", schematic: "valve" },
    evidenceLinks: commonEvidence("ball-valves"),
    sourceStatus: "catalog",
    confidence: 0.45,
    metadata: { pilot: true },
  },
  {
    id: "ball-valve-dn32-return",
    category: "valve",
    name: "Кран шаровой DN32, обратка",
    manufacturer: "DN",
    model: "BV3232P",
    dimensions: { widthMm: 165, depthMm: 78, heightMm: 130 },
    serviceZones: { frontMm: 80, rearMm: 80, leftMm: 80, rightMm: 80 },
    technicalParameters: { dnMm: 32, valveType: "ball_valve" },
    connectionPoints: [
      { id: "inlet", type: "return", label: "Вход DN32", localX: 0, localY: 39, localZ: 1100, dnMm: 32, direction: "left", medium: "water", source: "pilot/catalog", confidence: 0.45, status: "catalog" },
      { id: "outlet", type: "return", label: "Выход DN32", localX: 165, localY: 39, localZ: 1100, dnMm: 32, direction: "right", medium: "water", source: "pilot/catalog", confidence: 0.45, status: "catalog" },
    ],
    symbols: { plan: "valve", schematic: "valve" },
    evidenceLinks: commonEvidence("ball-valves"),
    sourceStatus: "catalog",
    confidence: 0.45,
    metadata: { pilot: true },
  },
  {
    id: "ball-valve-dn25-gas",
    category: "valve",
    name: "Кран шаровой DN25, газ",
    manufacturer: "DN",
    model: "BV3232P",
    dimensions: { widthMm: 160, depthMm: 95, heightMm: 120 },
    serviceZones: { frontMm: 80, rearMm: 80, leftMm: 80, rightMm: 80 },
    technicalParameters: { dnMm: 25, valveType: "ball_valve" },
    connectionPoints: [
      { id: "inlet", type: "gas", label: "Вход DN25", localX: 0, localY: 48, localZ: 600, dnMm: 25, direction: "left", medium: "natural_gas", source: "pilot/catalog", confidence: 0.45, status: "catalog" },
      { id: "outlet", type: "gas", label: "Выход DN25", localX: 160, localY: 48, localZ: 600, dnMm: 25, direction: "right", medium: "natural_gas", source: "pilot/catalog", confidence: 0.45, status: "catalog" },
    ],
    symbols: { plan: "valve", schematic: "valve" },
    evidenceLinks: commonEvidence("ball-valves"),
    sourceStatus: "catalog",
    confidence: 0.45,
    metadata: { pilot: true },
  },
  {
    id: "boiler-250kw-dev",
    category: "dev_fixture",
    name: "DEV fixture: mock boiler 250 kW",
    dimensions: { widthMm: 900, depthMm: 1200, heightMm: 1600 },
    serviceZones: { frontMm: 1000, rearMm: 600, leftMm: 500, rightMm: 500 },
    technicalParameters: { devOnly: true },
    connectionPoints: [],
    symbols: { plan: "dev", schematic: "dev" },
    evidenceLinks: [],
    sourceStatus: "placeholder_dev",
    confidence: 0,
    metadata: { devFixture: true },
  },
];

export const getDefinition = (definitionId: string): EquipmentDefinition => {
  const definition = pilotEquipmentCatalog.find((item) => item.id === definitionId);
  if (!definition) throw new Error(`Unknown equipment definition: ${definitionId}`);
  return definition;
};
